/*
SQLyog Community v13.1.9 (64 bit)
MySQL - 8.0.30 
*********************************************************************
*/
/*!40101 SET NAMES utf8 */;

create table `banco` (
	`codigo` varchar (30),
	`nome` varchar (750),
	`url` varchar (750),
	`ispb` varchar (30),
	`participa_compe` char (3)
); 
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('001','BCO DO BRASIL S.A.','https://www.bb.com.br/site/','0','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('70','BRB - BCO DE BRASILIA S.A.','https://novo.brb.com.br/','208','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values(NULL,'Selic','https://www.bcb.gov.br/controleinflacao/taxaselic','38121','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('','Bacen','https://www.bcb.gov.br/','38166','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('539','SANTINVEST S.A. - CFI','https://santinvest.com.br/','122327','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('430','CCR SEARA','https://crediseara.com.br/','204963','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('272','AGK CC S.A.','https://www.agkcorretora.com.br/','250699','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('136','CONF NAC COOP CENTRAIS UNICRED','https://www.unicred.com.br/','315557','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('407','SEFER INVESTIMENTOS DTVM LTDA','https://www.seferinvestimentos.com.br/','329598','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('104','CAIXA ECONOMICA FEDERAL','https://www.caixa.gov.br/','360305','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('','STN','https://www.gov.br/tesouronacional/pt-br','394460','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('77','BANCO INTER','https://inter.co/','416968','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('423','COLUNA S.A. DTVM','https://www.colunadtvm.com.br/','460065','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('741','BCO RIBEIRAO PRETO S.A.','https://www.brp.com.br/','517645','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('330','BANCO BARI S.A.','https://bancobari.com.br/','556603','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('534','EWALLY IP S.A.','https://www.ewally.com.br/','714671','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('743','BANCO SEMEAR','https://www.bancosemear.com.br/','795423','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('100','PLANNER CV S.A.','https://www.planner.com.br/','806535','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('541','FDO GARANTIDOR CRÉDITOS','https://www.fgc.org.br/','954288','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('96','BCO B3 S.A.','https://www.b3.com.br/','997185','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('747','BCO RABOBANK INTL BRASIL S.A.','https://www.rabobank.com.br/','1023570','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('362','CIELO IP S.A.','https://www.cielo.com.br/','1027058','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('322','CCR DE ABELARDO LUZ','https://www.sulcrediab.com.br/website/','1073966','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('748','BCO COOPERATIVO SICREDI S.A.','https://www.sicredi.com.br/home/','1181521','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('578','SICRES','https://sicres.coop.br/historia','1235921','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('350','COOP DE AGRICULTORES E AEROPORTUÁRIOS DO BRASIL','https://www.bcb.gov.br/estabilidadefinanceira/cooperativacredito','1330387','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('752','BCO BNP PARIBAS BRASIL S A','https://brasil.bnpparibas/','1522368','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('379','CECM COOPERFORTE','https://www.cf.coop.br/','1658426','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('399','Kirton Bank','https://www.reclameaqui.com.br/bradesco/kirton-bank-s-a-banco-multiplo_PEUmOvXcCcVQzNJv/','1701201','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('378','BCO BRASILEIRO DE CRÉDITO S.A.','https://bancobbcdigital.com.br/','1852137','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('413','BCO BV S.A.','https://www.bv.com.br/','1858774','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('756','BANCO SICOOB S.A.','https://www.sicoob.com.br/','2038232','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('360','TRINUS CAPITAL DTVM','https://trinus.co/dtvm','2276653','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('757','BCO KEB HANA DO BRASIL S.A.','https://bancokebhana.com.br/','2318507','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('102','XP INVESTIMENTOS CCTVM S/A','https://www.xpi.com.br/','2332886','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('84','SISPRIME DO BRASIL - COOP','https://www.sisprimedobrasil.com.br/','2398976','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('591','BANVOX DTVM','https://maisretorno.com/gestores/banvox-distribuidora-de-titulos-e-irios-1','2671743','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('555','PAN CFI','https://www.bancopan.com.br/','2682287','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('180','CM CAPITAL MARKETS CCTVM LTDA','https://cmcapital.com.br/quem-somos/','2685483','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('66','BCO MORGAN STANLEY S.A.','https://www.morganstanley.com.br/','2801938','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('15','UBS BRASIL CCTVM S.A.','https://www.ubs.com/br/pt.html','2819125','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('143','TREVISO CC S.A.','https://trevisocambio.com.br/','2992317','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('','CIP SA Siloc','http://www.cipfirm.com/v2/','2992335','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('62','HIPERCARD BM S.A.','https://www.hipercard.com.br/','3012230','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('74','BCO. J.SAFRA S.A.','https://www.safra.com.br/','3017677','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('99','UNIPRIME COOPCENTRAL LTDA.','https://www.uniprime.com.br/singular/central','3046391','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('387','BCO TOYOTA DO BRASIL S.A.','https://institucional.bancotoyota.com.br/','3215790','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('326','PARATI - CFI S.A.','https://www.parati-cfi.com.br/','3311443','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('25','BCO ALFA S.A.','https://bancoalfa.com.br/','3323840','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('75','BANCO ABN AMRO CLEARING S.A.','https://www.abnamro.com/clearing/en/home','3532415','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('40','BCO CARGILL S.A.','http://bancocargill.com.br/','3609817','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('307','TERRA INVESTIMENTOS DTVM','https://www.terrainvestimentos.com.br/','3751794','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('385','CECM DOS TRAB.PORT. DA G.VITOR','https://apps.apple.com/br/app/credestiva/id1518812045','3844699','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('425','SOCINAL S.A. CFI','https://socinal.com.br/','3881423','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('190','SERVICOOP','https://servicoop.com.br/','3973814','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('296','OZ CORRETORA DE CÂMBIO S.A.','https://ozcambio.com.br/','4062902','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('63','BANCO BRADESCARD','https://www.bradescard.com.br/SiteBradescard/bradescard/','4184779','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('191','NOVA FUTURA CTVM LTDA.','https://www.novafutura.com.br/','4257795','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('382','FIDUCIA SCMEPP LTDA','https://fiduciascm.com.br/','4307598','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('64','GOLDMAN SACHS DO BRASIL BM S.A','https://www.goldmansachs.com/worldwide/brazil/','4332281','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('','CIP SA Sitraf','https://www.cip.com/','4391007','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('97','CREDISIS - CENTRAL DE COOPERATIVAS DE CRÉDITO LTDA.','https://credisis.com.br/','4632856','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('16','CCM DESP TRÂNS SC E RS','https://www.sicoob.com.br/web/sicoobcreditran/sicoob-creditran','4715685','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('299','BCO AFINZ S.A. - BM','https://afinz.com.br/','4814563','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('471','CECM SERV PUBL PINHÃO','https://creservpinhao.com.br/index.php/pages/sobre-nos','4831810','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('540','HBI SCD','https://somoshbi.com.br/','4849745','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('12','BANCO INBURSA','http://www.inbursa.com/','4866275','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('3','BCO DA AMAZONIA S.A.','https://www.bancoamazonia.com.br/','4902979','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('60','CONFIDENCE CC S.A.','https://www.confidencecambio.com.br/','4913129','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('37','BCO DO EST. DO PA S.A.','https://www.banpara.b.br/','4913711','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('359','ZEMA CFI S/A','https://www.zemafinanceira.com/','5351887','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('159','CASA CREDITO S.A. SCM','https://casadocredito.com.br/','5442029','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('85','COOPCENTRAL AILOS','https://www.ailos.coop.br/','5463212','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('400','COOP CREDITAG','https://www.bcb.gov.br/estabilidadefinanceira/cooperativacredito','5491616','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('429','CREDIARE CFI S.A.','https://www.crediare.com.br/','5676026','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('410','PLANNER SOCIEDADE DE CRÉDITO DIRETO','https://www.planner.com.br/','5684234','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('328','CECM FABRIC CALÇADOS SAPIRANGA','https://casadosdados.com.br/solucao/cnpj/cooperativa-de-economia-e-credito-mutuo-dos-fabricantes-de-calcados-de-sapiranga-ltda-05841967000110','5841967','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('548','RPW S.A. SCFI','https://emprestacapital.com.br/quem-somos/','6249129','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('36','BCO BBI S.A.','https://www.bradescobbi.com.br/Site/Home/Default.aspx','6271464','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('469','PICPAY INVEST','https://picpay.com/investimentos','7138049','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('394','BCO BRADESCO FINANC. S.A.','https://wwwsn.bradescofinanciamentos.com.br/bfportalcli/','7207996','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('4','BCO DO NORDESTE DO BRASIL S.A.','https://www.bnb.gov.br/','7237373','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('458','HEDGE INVESTMENTS DTVM LTDA.','https://www.hedgeinvest.com.br/','7253654','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('320','BCO CCB BRASIL S.A.','http://br.ccb.com/','7450604','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('189','HS FINANCEIRA','https://hsfinanceira.com.br/','7512441','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('105','LECCA CFI S.A.','https://www.lecca.com.br/','7652226','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('76','BCO KDB BRASIL S.A.','https://www.kdb.co.kr/BZCOWS00N01.act?wcmsPath=/hmp/ch/gm/ba/CHGMBA0200.html&GmBrnId=BZ&_mnuId=IHIHGM1004&GmMlngTc=pt&jobNotice=Y','7656500','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('82','BANCO TOPÁZIO S.A.','https://www.bancotopazio.com.br/','7679404','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('312','HSCM SCMEPP LTDA.','https://hscm.com.br/','7693858','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('195','VALOR SCD S.A.','https://valorfinanciamentos.com.br/','7799277','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('93','POLOCRED SCMEPP LTDA.','https://www.bcb.gov.br/estabilidadefinanceira/scmepp','7945233','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('391','CCR DE IBIAM','https://www.sulcrediibiam.com.br/','8240446','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('273','CCR DE SÃO MIGUEL DO OESTE','https://sulcredi.coop.br/','8253539','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('368','BCO CSF S.A.','https://www.carrefoursolucoes.com.br/','8357240','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('290','PAGSEGURO INTERNET IP S.A.','https://pagseguro.uol.com.br/','8561701','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('259','MONEYCORP BCO DE CÂMBIO S.A.','https://www.bancomoneycorp.com.br/en/','8609934','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('395','F D GOLD DTVM LTDA','https://www.dgolddtvm.com.br/','8673569','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('364','EFÍ S.A. - IP','https://sejaefi.com.br/','9089356','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('157','ICAP DO BRASIL CTVM LTDA.','https://www.anbima.com.br/pt_br/institucional/perfil-da-instituicao/instituicao/178effd8-3d32-427b-e053-ca42e10a0dd1/perfil/icap-do-brasil-corretora-de-titulos-e-valores-mobiliarios-ltda.htm','9105360','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('183','SOCRED SA - SCMEPP','https://www.socredsa.com.br/','9210106','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('14','STATE STREET BR S.A. BCO COMERCIAL','https://investors.statestreet.com/investor-news-events/press-releases/news-details/2021/State-Street-Expands-Capabilities-in-Latin-America-Region-01-13-2021/default.aspx','9274232','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('130','CARUANA SCFI','https://www.caruanafinanceira.com.br/','9313766','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('358','MIDWAY S.A. - SCFI','https://www.midway.com.br/','9464032','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('127','CODEPE CVC S.A.','https://www.codepe.com.br/','9512542','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('79','PICPAY BANK - BANCO MÚLTIPLO S.A','https://picpay.com/','9516419','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('141','MASTER BI S.A.','https://www.bancomasterbi.com.br/pt','9526594','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('340','SUPERDIGITAL I.P. S.A.','https://superdigital.com.br/','9554480','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('81','BANCOSEGURO S.A.','https://www.bancoseguro.com.br/','10264663','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('475','BCO YAMAHA MOTOR S.A.','https://www.yamaha-motor.com.br/','10371492','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('133','CRESOL CONFEDERAÇÃO','https://cooperativismodecredito.coop.br/cenario-mundial/cenario-brasileiro/sistema-cresol/','10398952','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('323','MERCADO PAGO IP LTDA.','https://www.mercadopago.com.br/','10573521','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('577','AF DESENVOLVE SP S.A.','https://www.desenvolvesp.com.br/','10663610','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('121','BCO AGIBANK S.A.','https://agibank.com.br/','10664513','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('83','BCO DA CHINA BRASIL S.A.','https://www.bankofchina.com/br/pt/aboutus/','10690848','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('138','GET MONEY CC LTDA','http://getmoney.com.br/','10853017','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('24','BCO BANDEPE S.A.','https://www.santander.com.br/','10866788','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('384','GLOBAL SCM LTDA','https://www.bancodata.com.br/relatorio/11165756/','11165756','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('426','NEON FINANCEIRA - CFI S.A.','https://neon.com.br/','11285104','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('576','MERCADO BITCOIN IP LTDA','https://www.mercadobitcoin.com.br/pay','11351086','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('664','EAGLE IP LTDA.','https://www.grupo-eagle.com/','11414839','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('88','BANCO RANDON S.A.','https://ib.bancorandon.com/','11476673','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('319','OM DTVM LTDA','https://www.ourominas.com/om/quem-somos','11495073','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('274','BMP SCMEPP LTDA','https://www.bcb.gov.br/estabilidadefinanceira/scmepp','11581339','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('95','TRAVELEX BANCO DE CÂMBIO S.A.','https://www.travelexbank.com.br/','11703662','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('94','BANCO FINAXIS','https://finaxis.com.br/','11758741','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('478','GAZINCRED S.A. SCFI','https://homol-gazincred.gazin.com.br/quem-somos','11760553','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('276','BCO SENFF S.A.','https://www.senff.com.br/','11970623','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('447','MIRAE ASSET (BRASIL) CCTVM LTDA.','https://corretora.miraeasset.com.br/','12392983','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('569','CONTA PRONTA IP','https://contapronta.com.br/','12473687','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('47','BCO DO EST. DE SE S.A.','https://www.banese.com.br/','13009717','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('144','EBURY BCO DE CÂMBIO S.A.','https://br.ebury.com/','13059145','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('332','ACESSO SOLUÇÕES DE PAGAMENTO S.A. - INSTITUIÇÃO DE PAGAMENTO','https://www.reclameaqui.com.br/acesso/quem-e-a-13-140-088-acesso-solucoes-de-pagamento-s-a-que-aparece-no-meu_s7Z0nDAhFOhRd_vF/','13140088','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('450','FITBANK IP','https://fitbank.com.br/','13203354','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('126','BR PARTNERS BI','https://www.brpartners.com.br/pt-BR/home.html','13220493','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('325','ÓRAMA DTVM S.A.','https://www.orama.com.br/','13293225','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('301','DOCK IP S.A.','https://dock.tech/sac/','13370835','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('173','BRL TRUST DTVM SA','https://www.brltrust.com.br/','13486793','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('331','OSLO CAPITAL DTVM SA','https://framcapital.com/','13673855','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('119','BCO WESTERN UNION','https://www.westernunion.com/br/pt/home.html','13720915','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('396','HUB IP S.A.','https://www.hubfintech.com.br/','13884775','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('509','CELCOIN IP S.A.','https://www.celcoin.com.br/','13935893','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('254','PARANA BCO S.A.','https://www.paranabanco.com.br/v2','14388334','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('268','BARI CIA HIPOTECÁRIA','https://bancobari.com.br/','14511781','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('401','IUGU IP S.A.','https://www.iugu.com/','15111975','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('107','BCO BOCOM BBM S.A.','https://www.bocombbm.com.br/','15114366','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('334','BANCO BESA S.A.','https://pt.wikipedia.org/wiki/Banco_Econ%C3%B3mico_(Angola)','15124464','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('412','SOCIAL BANK S/A','http://www.br.ccb.com/en/','15173776','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('124','BCO WOORI BANK DO BRASIL S.A.','https://wooribank.com.br/','15357060','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('549','INTRA DTVM','https://www.intrainvestimentos.com.br/','15489568','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('149','FACTA S.A. CFI','https://factaonline.com.br/','15581638','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('197','STONE IP S.A.','https://www.stone.com.br/','16501555','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('439','ID CTVM','https://idsf.com.br/','16695922','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('142','BROKER BRASIL CC LTDA.','https://www.brokerbrasilcambio.com.br/','16944141','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('529','PINBANK IP','http://www.pinbank.com.br/','17079937','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('389','BCO MERCANTIL DO BRASIL S.A.','https://bancomercantil.com.br/','17184037','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('634','BCO TRIANGULO S.A.','https://www.tribanco.com.br/institucional/','17351180','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('545','SENSO CCVM S.A.','https://sensoinvestimentos.com.br/','17352220','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('132','ICBC DO BRASIL BM S.A.','https://www.icbcbr.com.br/pt/page/721852497324179476.html','17453575','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('298','VIPS CC LTDA.','https://vipscorretoradecambio.com.br/','17772370','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('377','BMS SCD S.A.','https://bancobms.com.br/','17826860','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('321','CREFAZ SCMEPP SA','https://site.crefaz.com.br/','18188384','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('542','CLOUDWALK IP LTDA','https://www.cloudwalk.io/','18189547','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('260','NU PAGAMENTOS - IP','https://nubank.com.br/','18236120','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('470','CDC SCD S.A.','https://www.cdcbank.com.br/','18394228','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('129','UBS BRASIL BI S.A.','https://www.ubs.com/br/pt.html','18520834','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('562','AZIMUT BRASIL DTVM LTDA','https://www.azimutbrasil.com.br/','18684408','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('128','BRAZA BANK S.A. BCO DE CÂMBIO','https://www.brazabank.com.br/','19307785','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('416','LAMARA SCD S.A.','https://www.bancodata.com.br/relatorio/19324634/','19324634','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('595','ZOOP MEIOS DE PAGAMENTO','https://www.zoop.com.br/','19468242','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('461','ASAAS IP S.A.','https://www.asaas.com/','19540550','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('194','UNIDA DTVM LTDA','https://www.parmetal.com.br/','20155248','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('538','SUDACRED SCD S.A.','https://www.sudacred.com.br/','20251847','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('588','PROVER PROMOCAO DE VENDAS IP LTDA.','https://www.econodata.com.br/consulta-empresa/20308187000283-PROVER-PROMOCAO-DE-VENDAS-INSTITUICAO-DE-PAGAMENTO-LTDA','20308187','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('561','PAY4FUN IP S.A.','https://www.p4f.com/','20757199','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('536','NEON PAGAMENTOS S.A. IP','https://neon.com.br/','20855875','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('383','EBANX IP LTDA.','https://www.ebanx.com/pt-br/','21018182','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('324','CARTOS SCD S.A.','https://www.cartos.com.br/','21332862','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('560','MAG IP LTDA.','https://www.magfinancas.com.br/','21995256','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('533','SRM BANK','https://www.srmasset.com/sobrenos','22575466','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('310','VORTX DTVM LTDA.','https://www.vortx.com.br/','22610500','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('380','PICPAY','https://picpay.com/','22896431','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('566','FLAGSHIP IP LTDA','https://ipflagship.com.br/','23114447','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('280','WILL FINANCEIRA S.A.CFI','https://www.willbank.com.br/','23862762','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('146','GUITTA CC LTDA','https://www.guitta.com.br/','24074692','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('343','FFA SCMEPP LTDA.','https://www.bcb.gov.br/estabilidadefinanceira/scmepp','24537861','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('651','PAGARE IP S.A.','https://www.pagare.app/','25104230','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('593','TRANSFEERA IP S.A.','https://transfeera.com/','27084098','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('335','BANCO DIGIO','https://www.digio.com.br/','27098060','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('349','AL5 S.A. CFI','https://al5bank.com.br/abra-sua-conta/','27214112','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('427','CRED-UFES','https://portal.ocbes.coop.br/pt/cooperativismo/cooperativas-registradas/cred-ufes/','27302181','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('374','REALIZE CFI S.A.','https://www.realizesolucoesfinanceiras.com.br/','27351731','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('278','GENIAL INVESTIMENTOS CVM S.A.','https://www.genialinvestimentos.com.br/','27652684','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('271','IB CCTVM S.A.','https://ibcambioeinvestimentos.com/','27842177','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('21','BCO BANESTES S.A.','http://banestes.com.br/','28127603','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('246','BCO ABC BRASIL S.A.','https://www.abcbrasil.com.br/','28195667','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('292','GALAPAGOS DTVM S.A.','https://galapagoscapital.com/','28650236','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('0','Balcão B3','https://www.b3.com.br/','28719664','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('554','STONEX BANCO DE CÂMBIO S.A.','https://banco.stonex.com/','28811341','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('','CIP SA C3','https://www.cip.com/','29011780','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('751','Scotiabank Brasil','https://www.br.scotiabank.com/','29030467','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('352','TORO CTVM S.A.','https://www.toroinvestimentos.com.br/','29162769','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('208','BANCO BTG PACTUAL S.A.','https://www.btgpactual.com/','30306294','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('386','NU FINANCEIRA S.A. CFI','https://comunidade.nubank.com.br/t/nu-pagamentos-x-nu-financeira-saiba-a-diferen%C3%A7a/33158','30680829','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('746','BCO MODAL S.A.','https://www.modalmais.com.br/quem-somos/','30723886','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('557','PAGPRIME IP','https://ppbank.com.br/','30944783','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('546','U4C INSTITUIÇÃO DE PAGAMENTO S.A.','https://www.u4c.com.br/','30980539','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('241','BCO CLASSICO S.A.','https://www.bancoclassico.com.br/','31597552','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('398','IDEAL CTVM S.A.','https://idealctvm.com.br/','31749596','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('336','BCO C6 S.A.','https://www.c6bank.com.br/','31872495','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('612','BCO GUANABARA S.A.','https://www.bancoguanabara.com.br/','31880826','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('604','BCO INDUSTRIAL DO BRASIL S.A.','https://www.bib.com.br/','31895683','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('505','BCO CREDIT SUISSE S.A.','https://www.credit-suisse.com/br/pt.html','32062580','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('550','BEETELLER','https://beeteller.com/','32074986','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('552','UZZIPAY IP S.A.','https://uzzipay.com/','32192325','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('329','QI SCD S.A.','https://qitech.com.br/','32402502','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('196','FAIR CC S.A.','http://www.faircorretora.com.br/','32648370','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('342','CREDITAS SCD','https://www.creditas.com/canais-de-atendimento','32997490','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('567','MERCANTIL FINANCEIRA','https://analitica.auvp.com.br/ativos/MERC3','33040601','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('300','BCO LA NACION ARGENTINA','https://www.bna.com.ar/','33042151','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('477','CITIBANK N.A.','https://www.citi.com/','33042953','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('266','BCO CEDULA S.A.','http://www.bancocedula.com.br/','33132044','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('122','BCO BRADESCO BERJ S.A.','https://exame.com/negocios/banco-berj-passa-agora-a-se-chamar-banco-bradesco-berj-2/','33147315','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('376','BCO J.P. MORGAN S.A.','https://www.jpmorgan.com.br/pt/about-us','33172537','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('348','BCO XP S.A.','https://www.xpi.com.br/','33264668','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('473','BCO CAIXA GERAL BRASIL S.A.','http://www.bcgbrasil.com.br/Areas-atuacao/Paginas/Banco-Caixa-Geral-Brasil.aspx','33466988','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('745','BCO CITIBANK S.A.','https://corporateportal.brazil.citibank.com/index.html','33479023','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('120','BCO RODOBENS S.A.','https://www.rodobens.com.br/','33603457','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('265','BCO FATOR S.A.','https://banco.fator.com.br/','33644196','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('7','BNDES','https://www.bndes.gov.br/wps/portal/site/home','33657248','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('583','CCC POUP INV DO CENTRO NORTE DO BRASIL','https://www.econodata.com.br/consulta-empresa/33667205001075-COOPERATIVA-CENTRAL-DE-CREDITO-POUPANCA-E-INVESTIMENTO-DO-CENTRO-NORTE-DO-BRASIL-CENTRAL-SICREDI-CENTRO-NORTE','33667205','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('582','CCC POUP INV DE MS, GO, DF E TO','https://assembleia.sintracoopms.com.br/wp-content/uploads/2024/08/PROPOSTA-ACT-SICREDI-MS-2024-2025.pdf','33737818','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('188','ATIVA S.A. INVESTIMENTOS CCTVM','https://www.ativainvestimentos.com.br/','33775974','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('134','BGC LIQUIDEZ DTVM LTDA','https://www.bgcliquidez.com/','33862244','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('719','BANCO MASTER MÚLTIPLO','https://www.bancomaster.com.br/','33884941','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('29','BANCO ITAÚ CONSIGNADO S.A.','https://www.itau.com.br/emprestimos-financiamentos/atendimento-consignado','33885724','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('467','MASTER S/A CCTVM','https://www.bancomaster.com.br/o-banco-master/sobre-nos','33886862','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('243','BANCO MASTER','https://www.bancomaster.com.br/','33923798','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('397','LISTO SCD S.A.','https://www.soulisto.com.br/','34088029','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('78','HAITONG BI DO BRASIL S.A.','https://www.haitongib.com.br/','34111187','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('525','INTERCAM CC LTDA','https://intercam.com.br/','34265629','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('355','ÓTIMO SCD S.A.','https://www.otimoscd.com.br/','34335592','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('531','BMP SCD S.A.','https://moneyp.com.br/sobre/','34337707','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('597','ISSUER IP LTDA.','https://issuer.com.br/','34747388','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('528','REAG TRUST DTVM','https://reag.com.br/','34829992','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('659','ONEKEY PAYMENTS IP S.A.','https://www.onekeypayments.com/','35210410','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('445','PLANTAE CFI','https://www.plantaeagrocredito.com.br/','35551187','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('586','Z1 IP LTDA.','https://www.z1.app/old-home','35810871','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('373','UP.P SEP S.A.','https://upp.com.br/','35977097','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('111','OLIVEIRA TRUST DTVM S.A.','https://www.oliveiratrust.com.br/','36113876','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('512','FINVEST DTVM','https://www.finvestdtvm.com.br/','36266751','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('599','AGORACRED S/A SCFI','https://www.agoracred.com.br/','36321990','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('516','QISTA S.A. CFI','https://www.souqista.com.br/','36583700','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('408','BONUSPAGO SCD S.A.','https://bonuspago.com.br/','36586946','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('484','MAF DTVM SA','http://mafdtvm.com.br/','36864992','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('402','COBUCCIO S.A. SCFI','http://grupoadrianocobuccio.com.br/empresas-do-grupo/cobuccio-sociedade-de-credito-direto.html','36947229','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('507','SCFI EFÍ S.A.','https://sejaefi.com.br/sobre-a-efi','37229413','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('404','SUMUP SCD S.A.','https://www.sumup.com/pt-br/','37241230','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('418','ZIPDIN SCD S.A.','https://zipdin.com.br/','37414009','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('414','LEND SCD S.A.','https://lend.tech/pt','37526080','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('449','DM','https://www.vocedm.com.br/portal/','37555231','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('587','FIDD DTVM LTDA.','https://www.fiddgroup.com/','37678915','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('518','MERCADO CRÉDITO SCFI S.A.','https://www.reclameaqui.com.br/mercado-pago/mercado-credito-sociedade-de-credito-financiamento-e-investimento-sa_jZ9DDnzIlxt9Qqgp/','37679449','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('406','ACCREDITO SCD S.A.','https://www.accredito-scd.com.br/Institucional','37715993','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('403','CORA SCFI','https://www.cora.com.br/','37880206','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('419','NUMBRS SCD S.A.','https://www.numbrs.com.br/','38129006','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('435','DELCRED SCD S.A.','https://delcred.com.br/','38224857','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('455','FÊNIX DTVM LTDA.','https://fenixdtvm.com.br/','38429045','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('544','MULTICRED SCD S.A.','https://multicredscd.com.br/','38593706','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('421','CC LAR CREDI','https://www.larcredi.com.br/','39343350','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('443','CREDIHOME SCD','https://credihome.com.br/','39416705','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('535','OPEA SCD','https://www.opeacapital.com/pt/','39519944','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('457','UY3 SCD S/A','https://www.uy3.com.br/','39587424','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('428','CREDSYSTEM SCD S.A.','https://www.credsystem.com.br/','39664698','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('448','HEMERA DTVM LTDA.','https://hemeradtvm.com.br/','39669186','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('452','CREDIFIT SCD S.A.','https://www.credifit.com.br/','39676772','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('510','FFCRED SCD S.A.','https://ffcredscd.com.br/emprestimo','39738065','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('462','STARK SCD S.A.','https://starkbank.com/br/','39908427','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('465','CAPITAL CONSIG SCD S.A.','https://www.capitalconsig.com.br/home.html','40083667','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('563','PROTEGE PAY CASH IP S.A.','https://www.paycashprotege.com.br/','40276692','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('306','PORTOPAR DTVM LTDA','https://www.bancodata.com.br/relatorio/40303299/','40303299','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('556','PROSEFTUR','https://www.proseftur.com.br/','40333582','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('305','FOURTRADE COR. DE CAMBIO LTDA','http://www.fourtrade.com.br/','40353377','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('463','AZUMI DTVM','https://azumidtvm.com.br/','40434681','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('590','REPASSES FINANCEIROS E SOLUCOES TECNOLOGICAS IP S.A.','https://aarin.com.br/','40473435','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('451','J17 - SCD S/A','https://www.j17bank.com.br/','40475846','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('444','TRINUS SCD S.A.','https://trinus.co/scd','40654622','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('519','LIONS TRUST DTVM','https://www.lionstrust.com.br/','40768766','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('454','MÉRITO DTVM LTDA.','https://merito.inc/servicos-financeiros/','41592532','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('460','UNAVANTI SCD S/A','https://www.unavanti.com.br/','42047025','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('506','RJI','https://rjicv.com.br/','42066258','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('482','SBCASH SCD','https://www.bancodata.com.br/relatorio/42259084/','42259084','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('17','BNY MELLON BCO S.A.','https://www.bnymellon.com/us/en/about-us/locations/latin-america-caribbean/brazil.html','42272526','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('174','PEFISA S.A. - C.F.I.','https://www.pefisa.com.br/','43180355','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('481','SUPERLÓGICA SCD S.A.','https://superlogica.com/','43599047','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('521','PEAK SEP S.A.','https://www.peakinvest.com.br/','44019481','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('433','BR-CAPITAL DTVM S.A.','https://www.unitas.com.br/site/','44077014','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('495','BCO LA PROVINCIA B AIRES BCE','https://www.bancoprovincia.com.ar/home/','44189447','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('523','HR DIGITAL SCD','https://hrdigitalscd.com.br/','44292580','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('527','ATICCA SCD S.A.','https://aticca.com.br/','44478623','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('511','MAGNUM SCD','https://www.magnumscd.com.br/','44683140','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('520','SOMAPAY SCD S.A.','https://somapay.com.br/','44705774','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('513','ATF SCD S.A.','https://www.atfbank.com/','44728700','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('125','BANCO GENIAL','https://www.genialinvestimentos.com.br/','45246410','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('547','BNK DIGITAL SCD S.A.','https://www.bdigital.com.br/','45331622','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('592','MAPS IP LTDA.','https://mapsip.com.br/','45548763','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('532','EAGLE SCD S.A.','https://www.eaglescd.com.br/','45745537','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('537','MICROCASH SCMEPP LTDA.','https://www.bcb.gov.br/estabilidadefinanceira/scmepp','45756448','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('524','WNT CAPITAL DTVM','https://www.wntdtvm.com/','45854066','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('526','MONETARIE SCD','https://monetarie.com.br/','46026562','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('488','JPMORGAN CHASE BANK','https://www.chase.com/','46518205','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('558','QI DTVM LTDA.','https://www.qidtvm.com.br/','46955383','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('522','RED SCD S.A.','https://www.accredito-scd.com.br/Institucional','47593544','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('530','SER FINANCE SCD S.A.','https://www.bcb.gov.br/estabilidadefinanceira/fintechs','47873449','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('575','DGBK CREDIT S.A. - SOCIEDADE DE CRÉDITO DIRETO.','https://www.bancodata.com.br/relatorio/48584954/','48584954','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('594','ASA SOCIEDADE DE CRÉDITO DIRETO S.A.','https://asa.com.br/','48703388','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('553','PERCAPITAL SCD S.A.','https://percapital.com.br/','48707451','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('65','BCO ANDBANK S.A.','https://www.andbank.com/brasil/','48795256','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('551','VERT DTVM LTDA.','https://www.vortx.com.br/investidor/fundos-investimento','48967968','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('559','KANASTRA SCD','https://kanastra.com.br/','49288113','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('579','QUADRA SCD','https://quadrascd.com.br/','49555647','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('619','TRIO IP LTDA.','https://www.triohq.com/pt-BR','49931906','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('568','BRCONDOS SCD S.A.','https://brcondos.com.br/','49933388','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('145','LEVYCAM CCV LTDA','https://www.levycam.com.br/','50579044','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('250','BANCO BMG CONSIGNADO S.A.','https://www.bancobmg.com.br/emprestimo/consignado/','50585090','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('585','SETHI SCD SA','https://www.sethisolucoesfinanceiras.com.br/boletos','50946592','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('589','G5 SCD SA','https://g5partners.com/','51212088','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('620','REVOLUT SCD S.A.','https://www.revolut.com/pt-BR/','51342763','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('572','ALL IN CRED SCD S.A.','https://www.zilicred.com.br/como-funciona/','51414521','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('614','NITRO SCD S.A.','https://sejanitro.com.br/','52440987','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('269','BCO HSBC S.A.','https://www.hsbc.com.mx/','53518684','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('213','BCO ARBI S.A.','https://www.bancoarbi.com.br/','54403563','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('0','Câmara B3','https://www.b3.com.br/en_us/','54641030','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('644','321 SCD S.A.','https://321bank.com.br/','54647259','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('139','INTESA SANPAOLO BRASIL S.A. BM','https://www.intesasanpaolobrasil.com.br/pt/','55230916','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('661','FREEX CC S.A.','https://freexcambio.com.br/','55428859','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('18','BCO TRICURY S.A.','https://bancotricury.com.br/','57839805','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('422','BCO SAFRA S.A.','https://www.safra.com.br/','58160789','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('630','BCO LETSBANK S.A.','https://www.letsbank.com.br/','58497702','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('224','BCO FIBRA S.A.','https://bancofibra.com.br/','58616418','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('393','BCO VOLKSWAGEN S.A','https://www.vwfs.com.br/','59109165','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('600','BCO LUSO BRASILEIRO S.A.','https://bancoluso.com.br/','59118133','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('390','BCO GM S.A.','https://www.chevroletsf.com.br/pt-br/inicio.html','59274605','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('623','BANCO PAN','https://www.bancopan.com.br/','59285411','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('655','BCO VOTORANTIM S.A.','https://www.bv.com.br/','59588111','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('479','BCO ITAUBANK S.A.','https://www.itau.com.br/','60394079','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('456','BCO MUFG BRASIL S.A.','https://www.br.bk.mufg.jp/','60498557','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('464','BCO SUMITOMO MITSUI BRASIL S.A.','https://www.smbcgroup.com.br/','60518222','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('341','ITAÚ UNIBANCO S.A.','https://www.itau.com.br/','60701190','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('237','BCO BRADESCO S.A.','https://www.bradescori.com.br/en/','60746948','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('381','BCO MERCEDES-BENZ S.A.','https://www.bancomercedes-benz.com.br/','60814191','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('613','OMNI BANCO S.A.','https://www.omni.com.br/','60850229','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('637','BCO SOFISA S.A.','https://www.sofisadireto.com.br/','60889128','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('0','Câmbio B3','https://www.b3.com.br/pt_br/produtos-e-servicos/compensacao-e-liquidacao/clearing-de-cambio/','60934221','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('653','BANCO VOITER','https://www.voiter.com/','61024352','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('69','BCO CREFISA S.A.','https://www.crefisa.com.br/','61033106','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('370','BCO MIZUHO S.A.','https://www.mizuhogroup.com/americas/brazil','61088183','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('249','BANCO INVESTCRED UNIBANCO S.A.','https://www.bancoinvest.pt/','61182408','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('318','BCO BMG S.A.','https://www.bancobmg.com.br/','61186680','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('626','BCO C6 CONSIG','https://www.c6bank.com.br/','61348538','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('508','AVENUE SECURITIES DTVM LTDA.','https://avenue.us/','61384004','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('366','BCO SOCIETE GENERALE BRASIL','https://societegeneralebrasil.com.br/site/','61533584','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('113','NEON CTVM S.A.','https://www.anbima.com.br/pt_br/institucional/perfil-da-instituicao/instituicao/178effd8-3192-427b-e053-ca42e10a0dd1/perfil/magliano-s-a-corretora-de-cambio-e-valores-mobiliarios.htm','61723847','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('131','TULLETT PREBON BRASIL CVC LTDA','http://www.tullettprebon.com.br/','61747085','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('11','C.SUISSE HEDGING-GRIFFO CV S/A','https://imobiliario.cshg.com.br/','61809182','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('611','BCO PAULISTA S.A.','http://www.bancopaulista.com.br/','61820817','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('755','BOFA MERRILL LYNCH BM S.A.','https://bofabrasil.com.br/PHXBrazil/BrazilCMS/','62073200','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('89','CREDISAN CC','https://portal.credisan.com.br/','62109566','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('643','BCO PINE S.A.','https://www.pine.com/','62144175','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('140','NU INVEST CORRETORA DE VALORES S.A.','https://www.nuinvest.com.br/','62169875','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('707','BCO DAYCOVAL S.A','https://www.daycoval.com.br/','62232889','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('288','CAROL DTVM LTDA.','https://inter.co/inter-dtvm/','62237649','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('363','SINGULARE CTVM S.A.','https://www.singulare.com.br/','62285390','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('101','RENASCENCA DTVM LTDA','https://www.dtvm.com.br/quem-somos','62287735','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('487','DEUTSCHE BANK S.A.BCO ALEMAO','https://country.db.com/brazil/?language_id=1&kid=brazil-sl.redirect-en.shortcut','62331228','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('233','BANCO CIFRA','https://www.dnb.com/business-directory/company-profiles.banco_cifra_sa.c53d0ac986a08ea19b961b5f9fd104c9.html','62421979','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('177','GUIDE','https://www.guide.com.br/','65913436','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('438','TRUSTEE DTVM LTDA.','https://www.trusteedtvm.com.br/','67030395','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('365','SIMPAUL','https://www.simpaul.com.br/','68757681','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('633','BCO RENDIMENTO S.A.','https://www.rendimento.com.br/','68900810','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('581','CENTRAL NORDESTE','https://www.sicredi.com.br/site/sobre-nos/relatorios/demonstracoes-financeiras-cooperativas-central-sicredi-nordeste/','70119680','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('218','BCO BS2 S.A.','https://www.bancobs2.com.br/','71027866','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('293','LASTRO RDV DTVM LTDA','https://lastro.com.br/a-empresa/','71590442','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('285','FRENTE CC S.A.','https://frentecorretora.com.br/','71677850','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('514','EXIM CC LTDA.','https://br.linkedin.com/company/exim-corretora','73302408','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('80','B&T CC LTDA.','https://btcambio.com.br/','73622748','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('565','ÁGORA CTVM S.A.','https://www.agorainvestimentos.com.br/','74014747','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('753','NOVO BCO CONTINENTAL S.A. - BM','https://nbcbank.com.br/','74828799','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('222','BCO CRÉDIT AGRICOLE BR S.A.','https://www.ca-cib.com/pt-br/brasil','75647891','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('281','CCR COOPAVEL','https://credicoopavel.com.br/','76461557','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('754','BANCO SISTEMA','https://bancosbrasil.com.br/servicos/banco-sistema-sa/148','76543115','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('98','CREDIALIANÇA CCR','https://site.credialianca.com.br/','78157146','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('610','BCO VR S.A.','https://bancovr.com.br/banco-vr/home/','78626983','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('712','OURIBANK S.A.','https://www.ouribank.com/','78632767','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('584','CCC POUP E INV DOS ESTADOS DO PR, SP E RJ','https://www.sistemaocesp.coop.br/?a=cooperativas&c=3266','80230774','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('720','BCO RNX S.A.','https://bancornx.com.br/','80271455','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('10','CREDICOAMO','https://www.credicoamo.com.br/index','81723108','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('440','CREDIBRF COOP','https://www.credibrf.com.br/','82096447','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('580','CCCPOUPINV SUL E SUDESTE - CENTRAL SUL/SUDESTE','https://www.bancodata.com.br/relatorio/87437687/','87437687','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('283','RB INVESTIMENTOS DTVM LTDA.','https://www.rbinvestimentos.com/','89960090','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('33','BCO SANTANDER (BRASIL) S.A.','https://www.santander.com.br/','90400888','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('646','DM SA CFI','https://www.vocedmfinanceira.com.br/','91669747','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('217','BANCO JOHN DEERE S.A.','https://www.deere.com.br/pt/financiamento/banco-john-deere/','91884981','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('41','BCO DO ESTADO DO RS S.A.','https://www.banrisul.com.br/','92702067','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('543','COOPCRECE','https://coopcrece.com.br/','92825397','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('117','ADVANCED CC LTDA','https://advancedcorretora.com.br/','92856905','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('654','BCO DIGIMAIS S.A.','https://www.bancodigimais.com.br/','92874270','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('371','WARREN CVMC LTDA','https://warren.com.br/','92875780','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('212','BANCO ORIGINAL','https://www.original.com.br/','92894922','S');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('289','EFX CC LTDA.','https://www.efxcambio.com.br/','94968518','N');
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('666','666','666.com',NULL,NULL);
insert into `banco` (`codigo`, `nome`, `url`, `ispb`, `participa_compe`) values('333','333','333.com',NULL,NULL);
